import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppBar from "@/components/header";
import Footer from "@/components/footer";
import { AOSInit } from "@/components/aos";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AOSInit />
        <div className="flex min-h-screen flex-col bg-white">
          <AppBar />
          <div className="flex-grow overflow-x-hidden">
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
